### PR TITLE
Make Extractor/Mp4 Atom Parsing code reusable by external custom mp4 …

### PR DESCRIPTION
**Pull request by colinkho**
…extractors

### CODE REVIEW

**Comment by icbaker** [comment]
Thanks for sending this. I'm going to submit some of this myself directly internally:
1. Move a couple of parsing methods from `Atom` to `AtomParsers`
2. Move `Atom` to `lib-container` and make it public (so it can in future be used by `muxer`)

Once these changes are submitted I'll let you know and you can rebase this change so it only has the `AtomParsers`, `Sniffer` and `TrackSampleTable` changes.

**Comment by icbaker** [comment]
The changes have been submitted:
* https://github.com/androidx/media/commit/9dfd72b6c62a56c569fad7af88fad61a549d2e17
* https://github.com/androidx/media/commit/9d008da356bd6e26f4f18a9dba48ce9741caad6b
* https://github.com/androidx/media/commit/ee27334f06f7c74618049e9ae99b7f002918aeee

The final change renamed `Atom` to `Mp4Box` for two reasons:
1. The 'box' terminology more closely matches the ISO 14496-12 spec.
2. Other MP4-specific files in `androidx.media3.container` are prefixed with `Mp4` instead of being in an `mp4` sub-package.

I suggest we rename `AtomParsers` to `BoxParsers` and keep it in the `extractor.mp4` package. We don't need to also touch every call-site, because it makes the blast radius of the change too large.

I don't mind if you do that in this PR, or we can do it directly as an internal change.

**Comment by colinkho** [comment]
@icbaker Rebased to capture your commits and renamed to BoxParsers. Thank you!

**Comment by icbaker** [comment]
I'm going to send this for internal review now. You may see some more commits being added as I make changes in response to review feedback. Please refrain from pushing any more substantive changes as it will complicate the internal review - thanks!

**Pull request merged**
