### PR TITLE
SntpClient periodically re-syncs the offset to NTP server

### PR DESCRIPTION
**Pull request by stevemayhew**
Many of the Android TV platforms do not report accurate `SystemClock.elapsedRealtime()` In addition this drift is not consistant accross multiple boxes, so the time offset between any pair of boxes will vary over time.

This variance will lead to a drift in the Live Offset calculation.

Fix is simple, inValidate the NTP server query after a period of time (10 minutes) and re-issue the call

### CODE REVIEW

**Comment by stevemayhew** [comment]
See bug #696

**Comment by stevemayhew** [comment]
@marcbaechinger as you can see, with Google TV time is off by 2 seconds from my workstation (which is a Ventura Mac synchronized to NTP):

````
smayhew2m-sjc1:ExoPlayer smayhew$ gdate -In ; adb -t 25 shell date -In
2023-10-05T11:14:15,121477000-07:00
2023-10-05T11:14:13,432206196-07:00
smayhew2m-sjc1:ExoPlayer smayhew$ 
smayhew2m-sjc1:ExoPlayer smayhew$ adb -t 25 shell getprop | grep fingerprint
[ro.bootimage.build.fingerprint]: [google/sabrina_prod_stable/sabrina:12/STTE.230319.008.H1/10319030:user/release-keys]
```
With this pull request and the one that fixes #702 we can play video on two devices synchronized.   We are shipping this feature on our 1.15 based ExoPlayer product, my company is graciously allowing me to share the required changes.

Let me know if you want a live HLS URL to play with I can sent it to a private email only.

**Comment by stevemayhew** [comment]
@marcbaechinger  do you want me to re-post this based to main?

**Comment by marcbaechinger** [comment]
Sorry for no hasving responded so far. Yes, please assign to me when done. I'll try to do better then this time.

**Comment by stevemayhew** [comment]
No worries @marcbaechinger, we are all busy at our respective day jobs.  I'll opened a pull request based to main as well with this same code change, already formatted in Google style.  https://github.com/androidx/media/pull/1794

**Review by linhai326 — APPROVED** [review]

**Comment by stevemayhew** [comment]
You may as well also approve and merge #1794 since it is the same code already merged to main branch.   Or you can simply close pull request.  Which ever is easier for you internal git process.

**Comment by marcbaechinger** [comment]
I'm closing this. Going to proceed with #1794 instead. Thanks Steve!

**Pull request closed without merging**
