### PR TITLE
Support file schemes in SimpleBitmapLoader

### LINKED ISSUE #108: Support File Uris in SimpleBitmapLoader
In our App the artwork file cache is simply placed inside the apps private directory.
I have added a custom BitmapLoader implementation to our project, but it would be just a few lines of code for SimpleBitmapLoader to alsosupport files.

### PR DESCRIPTION
**Pull request by tzugen**
Fixes #108

### CODE REVIEW

**Comment by tzugen** [comment]
Done!

**Comment by christosts** [comment]
I've left a comment on the code, I was wondering if you saw it?

**Comment by tzugen** [comment]
hm, i can't see any comment-

**Comment by christosts** [comment]
my bad, the comment should be published now

**Comment by tzugen** [comment]
I have update the comments in case you didn't get a notice :)

**Comment by christosts** [comment]
Thanks! I merged the PR, with some changes and unit tests. It should appear here once we update the main branch

**Pull request merged**
