### PR TITLE
Clean up code now that min SDK version is 21

### PR DESCRIPTION
**Pull request by MGaetan89**
This PR does some cleanup following the bump of the min SDK version from 19 to 21:
- Make sure to use `project.ext.minSdkVersion` wherever possible, instead of hardcoding the min SDK version.
- Remove usages of Multidex in every modules.
- Remove some legacy `SDK_INT` checks.

### CODE REVIEW

**Comment by MGaetan89** [comment]
I'm checking if `MediaSessionImplBase`, `MediaSessionImplApi18`, and `MediaSessionImplApi19` can also be removed. They appeared to be unused, so I guess they are remains of when the min SDK version was bumped to 19.

**Comment by MGaetan89** [comment]
> I'm checking if `MediaSessionImplBase`, `MediaSessionImplApi18`, and `MediaSessionImplApi19` can also be removed. They appeared to be unused, so I guess they are remains of when the min SDK version was bumped to 19.

Should be good for review now 👍🏻

**Comment by icbaker** [comment]
Thanks for the extra fixes! Please could you split out the changes in `androidx.media3.session.legacy` so we can park those for now? A lot of this code is already unused, so it makes sense to remove larger swathes of it before removing just these API-guarded bits.

**Comment by MGaetan89** [comment]
Sure, I'll do that 👍🏻 
Should I submit the changes to `androidx.media3.session.legacy` in a dedicated PR, or just remove them from this one?

**Comment by icbaker** [comment]
I think just remove them from this one, I don't think it's worth splitting them to another PR because there will be so many merge conflicts after we remove the 'wider' unused code.

**Comment by MGaetan89** [comment]
> I think just remove them from this one, I don't think it's worth splitting them to another PR because there will be so many merge conflicts after we remove the 'wider' unused code.

The changes have been reverted. I'll also rebase the PR on `main` to integrate the latest changes.

**Comment by icbaker** [comment]
I'm going to send this for internal review now. You may see some more commits being added as I make changes in response to review feedback. Please refrain from pushing any more substantive changes as it will complicate the internal review - thanks!

**Pull request merged**
